### ISSUE TITLE
Report bugs in Pandemic

### ISSUE THREAD

**Issue by youpengzhao** [GAIGResearch/TabletopGames#180]
Well, we intend to participate in COG 2022 competition of Pandemic so we execute the code. However, we discover some bugs and report them here. 
1. The diseases can not be cured in one action. To be specific, if we use the antidote or the skill of medic to cure the disease of one colour in a city, only one disease can be removed. However, according to the rules, all these diseases should be removed. We think it is a serious bug as it makes the role of medic useless.
2. The exchange of cards between players is unclear. If the players try to exchange the cards, we don't know who gives the card and who receives the card.
3. The turn order of the games may be disrupted after using the event cards, for example, one player may be given another action step while someone's turn may be skipped.

**Comment by rdgain** [comment]
Thanks for pointing these out! We'll investigate and have a fix up asap.

**Comment by youpengzhao** [comment]
Well, thank you for your updating. However, after running the program of newest version, we find that HumanGUIplayer can not work at all and HumanConsolePlayer also works strangely as it always says 'no available action' after only two actions in one turn, which we think will bring great difficulties to the training. What's more, when exchanging the card between players, we still don't know which card is exchanged. We hope these bugs can also be fixed. Thank you very much

**Comment by hopshackle** [comment]
Thanks for that - I've just tried the HumanGUIPlayer in a Pandemic game (with one other random player) using the current pandemic-competition branch, and it seems to work OK for me. (There was a bug, which was fixed yesterday morning - so I wanted to check you were using the latest version).

Could you then detail exactly what you're seeing with HumanGUIPlayer?

**Comment by youpengzhao** [comment]
Well, sorry for not giving a response timely. I download the project of latest version under pandemic-competition branch and try to run it. There still exists problem of HumanGUIPlayer. The picture is shown below. It seems that the code will get stuck when using HumanGUIplayer and HumanConsoleplayer. I remember that using old version can finish a game however current version can not do it. I don't know whether I configure the project mistakenly. Whereas since using randomplayer can operate normally, I think there may be still some unusual bugs.
![image](https://user-images.githubusercontent.com/48088351/161913022-47646489-26c7-4c09-86ae-f676dae3c4c2.png)

**Comment by youpengzhao** [comment]
Sorry for not giving a response timely. I used to use code downloaded from the main branch and the GUI will show all legal actions for choice. But the operation way of current version seems to be different from old version that I use. So I thought there are bugs. Sorry for that.

**Comment by youpengzhao** [comment]
Well, since current version changes the choice of action by clicking nodes in GUI, I think this brings new problems. Although medic can treat all diseases, other players' skills are hard to use, at least I don't know how to use them... Is there a readme file to tell us the information about the operations in the game? I think this will help a lot for developing the AI. Thank you very much.

**Comment by youpengzhao** [comment]
Thank you for your response. However, we find that when we execute the program using HumanGUIplayer, a bug will happen sometimes. The specific content is shown as below:
![image](https://user-images.githubusercontent.com/48088351/162563849-dd538658-3d2c-4073-bded-917caa96ae03.png)

**Comment by youpengzhao** [comment]
What's more, we don't know how to exchange cards between players and the website does not tell how this can be realised. We hope to know this information. Thank you very much.

**Comment by hopshackle** [comment]
Hi there,

Firstly, can I check that you are using the latest pandemic-competition branch? The error you report uses code that is in master, but not in pandemic-competition, so I suspect you might not have the latest pandemic version.

This latest pandemic version also includes the 'Share Knowledge' action to pass a card to another player (and the 'Researcher' special ability) - these are both explained in the GUI instructions at http://www.tabletopgames.ai/wiki/games/gui/pandemic. (However the Share Knowledge is not in the master branch - which may also explain why you are having some difficulty here).

And thank you for reporting your issues! It is very helpful to us to understand how people are using TAG.

(Separate answer to follow on the detailed meaning of parameters.)

**Comment by youpengzhao** [comment]
Well, thank you for your response. We have tested the code and execute it successfully. However, I encounter a strange problem. My teammate can run the project successfully but when I configure the project as him, it fails. There seems to be problems that some external libraries can not be imported. I want to know whether is there any advice about the configuration? 
![image](https://user-images.githubusercontent.com/48088351/162576958-54c0a54a-8449-4e47-8dc6-1d9a6c20abeb.png)

**Comment by hopshackle** [comment]
Those video libraries should be loaded automatically by Maven from the pom.xml.
```
        <dependency>
            <groupId>io.humble</groupId>
            <artifactId>humble-video-all</artifactId>
            <version>0.3.0</version>
        </dependency>
```
I've seen Maven sometimes not pick up changes to dependencies immediately in IntelliJ (are you using IntelliJ, or some other IDE?), so it may be worth 'Relloading all Maven projects'.

(Screenshot of button in IntelliJ in case this is helpful)

![MavenLoadArrow](https://user-images.githubusercontent.com/4341035/162793218-4a5c38ce-f065-4db0-b545-94bbb3727430.png)

**Comment by hopshackle** [comment]
Hi there,

To address your question on what the parameters for a Pandemic game mean, an explanation of these has now been added to the competition web page at http://www.tabletopgames.ai/competition/cog2022/
